/**
 * Shared singletons for the Test Suite webview.
 *
 * These objects are created once and mutated in place so every feature module
 * observes the same live state. Scalars that need reassignment (the Monaco
 * editor instance) are wrapped in a container object so the binding can be
 * shared across modules.
 */

// VS Code API (must be acquired exactly once per webview)
export const vscode = acquireVsCodeApi();

// Virtual scroll configuration
export const VIRTUAL_SCROLL = {
    itemHeight: 45,           // Height of each result item in pixels
    bufferSize: 10            // Extra items to render above/below visible area
};

// Virtual scroll state (mutated in place)
export const virtualScrollState = {
    startIndex: 0,
    endIndex: 0,
    scrollTop: 0
};

// Application state (mutated in place)
export const state = {
    suite: null,
    requests: [],
    environments: [],
    selectedEnvironment: null,
    dataFile: null,
    isRunning: false,
    results: [],           // Now stores compact ResultSummary objects (not full results)
    displayItems: [],      // Flat list of header + result rows for grouped virtual scroll
    collapsedGroups: new Set(), // Keys of collapsed collection/folder groups in the results list
    collapsedIterations: new Set(), // Iteration numbers collapsed in the results list
    statistics: null,
    passed: 0,
    failed: 0,
    skipped: 0,
    selectedResultIndex: -1,
    currentRunId: null,
    suiteId: null,
    autoScroll: true,
    totalRequests: 0,
    iterations: 1,
    isDirty: false,  // Track unsaved changes
    availableRequests: [],  // Available requests for Add modal
    runStartTime: null,      // Track start time for duration calculation
    // History state
    historyRuns: [],         // List of RunHistoryEntry objects
    viewingHistoryRun: null, // runId of loaded history run (null = live/latest)
    historyManifest: null,   // Manifest of loaded history run
    loadingAsLatest: false,  // Flag: loading the latest run (suppresses history banner)
    reportPath: null         // Path to the HTML report generated by the last run
};

// Monaco editor instance for response body (wrapped so it can be reassigned
// from any module via editorState.responseBodyMonacoEditor = ...)
export const editorState = {
    responseBodyMonacoEditor: null
};

// DOM Elements - populated in initialize() via Object.assign(elements, {...})
export const elements = {};
